In [98]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers,Model


# Generate dataset

In [99]:
def generate_data(num_of_data):
    X = np.random.randint(-15,15,size = num_of_data, dtype = int)
    Y = 5*X**3 -8*X**2-7*X+1
    return X,Y

In [100]:
x_data, y_data = generate_data(50000)

In [101]:
x_data


array([  1,  -8, -14, ...,  -9,  11,   2])

In [102]:
x_data =2*(x_data-min(x_data))/(max(x_data)-min(x_data))-1
y_data =2*(y_data-min(y_data))/(max(y_data)-min(y_data))-1

In [103]:
x_data



array([ 0.10344828, -0.51724138, -0.93103448, ..., -0.5862069 ,
        0.79310345,  0.17241379])

In [104]:
y_data

array([ 0.21212121,  0.0158046 , -0.7792581 , ..., -0.06347962,
        0.57915361,  0.21238245])

# Split dataset into train test and validation

In [105]:
train_x = x_data[:int(len(x_data)*.9)]
train_y = y_data[:int(len(y_data)*.9)]

val_x   = x_data[int(len(x_data)*.9):int(len(x_data)*.95)]
val_y   = y_data[int(len(y_data)*.9):int(len(y_data)*.95)]

test_x  = x_data[int(len(x_data)*.95):]
test_y  = y_data[int(len(y_data)*.95):]


In [106]:
train_x

array([ 0.10344828, -0.51724138, -0.93103448, ..., -0.44827586,
       -0.93103448, -0.31034483])

In [107]:
val_x


array([-0.79310345,  0.5862069 ,  0.24137931, ...,  0.65517241,
       -1.        ,  0.51724138])

In [108]:
test_x

array([-1.        , -0.93103448, -0.72413793, ..., -0.5862069 ,
        0.79310345,  0.17241379])

# Define Model architecture

In [109]:
inputs = layers.Input(shape =(1))
x      = layers.Dense(32, activation ='relu')(inputs)
x      = layers.Dense(64, activation ='relu')(x)
x      = layers.Dense(128, activation ='relu')(x)
outputs = layers.Dense(1,activation='linear')(x)

model  = Model(inputs = inputs, outputs = outputs)

In [110]:
model.summary()

Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_7 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense_24 (Dense)            (None, 32)                64        
                                                                 
 dense_25 (Dense)            (None, 64)                2112      
                                                                 
 dense_26 (Dense)            (None, 128)               8320      
                                                                 
 dense_27 (Dense)            (None, 1)                 129       
                                                                 
Total params: 10625 (41.50 KB)
Trainable params: 10625 (41.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# Compile and fit the model

In [111]:
model.compile(optimizer = tf.keras.optimizers.Adam(lr = 1e-4),loss = "mean_squared_error", metrics=['mae'])

In [ ]:
model.fit(train_x, train_y, epochs = 10, validation_data =(val_x,val_y))

Epoch 1/10
1407/1407 [==============================] - 7s 4ms/step - loss: 0.0022 - mae: 0.0152 - val_loss: 4.9520e-06 - val_mae: 0.0015
Epoch 2/10
1407/1407 [==============================] - 5s 4ms/step - loss: 2.7918e-05 - mae: 0.0023 - val_loss: 2.5549e-06 - val_mae: 0.0012
Epoch 3/10
1407/1407 [==============================] - 5s 4ms/step - loss: 1.9923e-05 - mae: 0.0012 - val_loss: 5.3036e-04 - val_mae: 0.0199
Epoch 4/10
1407/1407 [==============================] - 5s 3ms/step - loss: 1.4514e-05 - mae: 0.0017 - val_loss: 1.0050e-07 - val_mae: 2.4220e-04
Epoch 5/10
1407/1407 [==============================] - 5s 4ms/step - loss: 4.4061e-05 - mae: 0.0024 - val_loss: 3.2466e-07 - val_mae: 3.7179e-04
Epoch 6/10
1407/1407 [==============================] - 5s 4ms/step - loss: 4.2808e-07 - mae: 2.3093e-04 - val_loss: 8.4648e-05 - val_mae: 0.0064
Epoch 7/10
1338/1407 [===========================>..] - ETA: 0s - loss: 2.1560e-05 - mae: 0.0019